# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# modelExample.py
# Created on: 2020-05-23 01:09:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Abuja_Boundary_shp = "C:\\Users\\owner\\Downloads\\Sample_scripts\\ch01\\Abuja_Boundary.shp"
Distance__value_or_field_ = "10 Kilometers"
Output_Feature_Class = "C:\\Users\\owner\\Documents\\ArcGIS\\Default1.gdb\\Abuja_Boundary_Buffer"

# Process: Buffer
arcpy.Buffer_analysis(Abuja_Boundary_shp, Output_Feature_Class, Distance__value_or_field_, "FULL", "ROUND", "NONE", "")

